### ISSUE TITLE
it is not rendered

### ISSUE THREAD

**Issue by CrisMon-01** [leoCamilo/XamarinTutorial#1]
I see something that not work weel
 `  var stack = new StackLayout();
            var search = new SearchBar();
            var listView = new ListView();

            stack = new StackLayout();
            search = new SearchBar();
            listView = new ListView();

            stack.Children.Add(search);
            stack.Children.Add(listView);`

i have put this snippet because the yours not work well because you have rewrite var everytime and it was just declared, but this stack is not rendered on the page

**Comment by CrisMon-01** [comment]
i have find the solution is an Android 7.0 bug someother have the same problem on the searchbar

**Comment by leoCamilo** [comment]
Sorry not answer you before, this project was a college homework, so I don't keep doing things, I had this Android 7 render bug too in other project, so I had to set HeightRequest by my self to fix, but, specify the file and line you had the problem, and how you fixed, maybe can help someone else and I can learn something =)

**Comment by CrisMon-01** [comment]
Hi fix it with explicit the height for the searchbar, is a common issue,
i have see the solution on the xamarin forum

Sent from Mail for Windows 10
